### ISSUE TITLE
Multichannel Export

### ISSUE THREAD

**Issue by aokikamawara** [GameOfLife/WFSCollider#37]
Hi There-

I have been experimenting with wave-field spatialization in WFSCollider, but I'd like to export my work for 48 speakers into 48 mono audio files. Is there a way to do this with WFSCollider? I could not find any information about this. 

Thank You.

**Comment by woutersnoei** [comment]
Hi,

are you using a 48-channel wfs setup? You should be able to export your work as a 48 channel audio file using the "Score" -> "Export as audio file..." menu item, and then split it into mono files using another program (SoX should be able to do so, and perhaps some gui-based programs too). However, one issue that could come up here is that the file could become too large for the aiff file type (those can't be over 4GB unfortunately). If this is the case I can help you with a small change to the source code to make it export as .caf instead, then it should work fine. Let me know!

**Comment by aokikamawara** [comment]
Right now, I am only monitoring the audio in stereo preview mode. I have edited the speaker configuration in the Preferences to reflect the space I'd like to have audio files available for.  

"Score"->"Export as audio files.." seems to only put out an overblown stereo file when opened in a basic DAW (using Adobe Audition). Is SoX necessary?

**Comment by miguel-negrao** [comment]
In order to export the WFS output you need to boot WFSCollider in WFS mode, not in stereo preview mode. I suppose the manual might explain how to do that ?

**Comment by aokikamawara** [comment]
Aha, it's in there: "If you set the previewMode to ‘off’, that means that WFSCollider will not be in previewMode, but generate actual WFS rendering, based on the current WFS Speaker Configuration."  Breaking them up seems to be the harder part. 

Thanks.
